cvbuilder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('usercv.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usercv/urls.py
from django.urls import path
from . import views


app_name = 'usercv'

urlpatterns = [
    path('', views.index, name='cv-index'),
    path('<int:pk>/profile-update', views.ProfileUpdateView.as_view(), name='profile-update'),
    path('register', views.signup, name='user-signup'),
    path('user-profile', views.user_profile, name='user-profile'),
    path('about-create', views.AboutCreateView.as_view(), name='about-create'),
    path('<int:pk>/about-update', views.AboutUpdateView.as_view(), name='about-update'),
    path('education-create', views.EducationCreateView.as_view(), name='education-create'),
    path('<int:pk>/education-update', views.EducationUpdateView.as_view(), name='education-update'),
    path('career-create', views.CareerCreateView.as_view(), name='career-create'),
    path('<int:pk>/career-update', views.CareerUpdateView.as_view(), name='career-update'),
    path('course-create', views.CourseCreateView.as_view(), name='course-create'),
    path('<int:pk>/course-update', views.CourseUpdateView.as_view(), name='course-update'),
    path('experience-create', views.ExperienceCreateView.as_view(), name='experience-create'),
    path('<int:pk>/experience-update', views.ExperienceUpdateView.as_view(), name='experience-update'),
    path('portfolio-create', views.PortfolioCreateView.as_view(), name='portfolio-create'),
    path('<int:pk>/portfolio-update', views.PortfolioUpdateView.as_view(), name='portfolio-update'),
    path('skill-create', views.SkillCreateView.as_view(), name='skill-create'),
    path('<int:pk>/skill-update', views.SkillUpdateView.as_view(), name='skill-update'),
    path('hobby-create', views.HobbyCreateView.as_view(), name='hobby-create'),
    path('<int:pk>/hobby-update', views.HobbyUpdateView.as_view(), name='hobby-update'),
    path('language-create', views.LanguageCreateView.as_view(), name='language-create'),
    path('<int:pk>/language-update', views.LanguageUpdateView.as_view(), name='language-update'),
    path('cocurricular-create', views.CocurricularCreateView.as_view(), name='cocurricular-create'),
    path('<int:pk>/cocurricular-update', views.CocurricularUpdateView.as_view(), name='cocurricular-update'),
    path('reference-create', views.ReferenceCreateView.as_view(), name='reference-create'),
    path('<int:pk>/reference-update', views.ReferenceUpdateView.as_view(), name='reference-update'),

    path('create_cv', views.cv_view, name='create-cv'),
]

usercv/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.shortcuts import reverse


# Create your models here.
class Cv(models.Model):
    title = models.CharField(max_length=50, default='Section Title')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


class Profile(Cv):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    dob = models.DateField(null=True)
    website = models.URLField(null=True)
    address = models.CharField(max_length=20)
    city = models.CharField(max_length=20)

    def get_absolute_url(self):
        return reverse('usercv:user-profile')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, force_insert=False, force_update=False, using=None, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class About(Cv):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField(default='Section Description')

    def get_absolute_url(self):
        return reverse('usercv:user-profile')

    def save(self, force_insert=False, force_update=False, using=None, *args, **kwargs):
        super().save(*args, **kwargs)


class Career(Cv):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('usercv:user-profile')


class Education(Cv):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    school = models.CharField(max_length=70)
    start = models.DateField(null=True)
    end = models.DateField(null=True)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('usercv:user-profile')

    def save(self, force_insert=False, force_update=False, using=None, *args, **kwargs):
        super().save(*args, **kwargs)


class Course(Cv):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    start = models.DateField(null=True)
    end = models.DateField(null=True)
    school = models.CharField(max_length=40)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('usercv:user-profile')


class Experience(Cv):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.CharField(max_length=45)
    company = models.CharField(max_length=45)
    start = models.DateField(null=True)
    end = models.DateField(null=True)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('usercv:user-profile')


class Portfolio(Cv):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.TextField()
    link = models.URLField()
    cover = models.FileField()

    def get_absolute_url(self):
        return reverse('usercv:user-profile')


class Skill(Cv):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.TextField()
    level = models.PositiveIntegerField(default=10)

    def get_absolute_url(self):
        return reverse('usercv:user-profile')


class Hobby(Cv):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('usercv:user-profile')


class Language(Cv):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    level = models.TextField()

    def get_absolute_url(self):
        return reverse('usercv:user-profile')


class Cocurricular(Cv):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    activity = models.CharField(max_length=30)
    company = models.CharField(max_length=30)
    start = models.DateField(null=True)
    end = models.DateField(null=True)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('usercv:user-profile')


class Reference(Cv):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=40)
    company = models.CharField(max_length=55)
    phone = models.CharField(max_length=20)
    email = models.EmailField()

    def get_absolute_url(self):
        return reverse('usercv:user-profile')

usercv/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

usercv/views.py
from django.shortcuts import render, redirect
from django.views.generic import UpdateView, CreateView
from .models import Profile, About, Education, Career, Course, Experience, Portfolio, Skill, Hobby, Language, Cocurricular, Reference
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserForm
from django.contrib.auth import authenticate, login


# Create your views here.
def index(request):
    return render(request, 'usercv/index.html')


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = ['image', 'phone', 'email', 'dob', 'website', 'address', 'city']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AboutCreateView(CreateView):
    model = About
    fields = ['title', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AboutUpdateView(LoginRequiredMixin, UpdateView):
    model = About
    fields = ['title', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EducationCreateView(CreateView):
    model = Education
    fields = ['school', 'start', 'end', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EducationUpdateView(UpdateView):
    model = Education
    fields = ['school', 'start', 'end', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CareerCreateView(CreateView):
    model = Career
    fields = ['title', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CareerUpdateView(UpdateView):
    model = Career
    fields = ['title', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CourseCreateView(CreateView):
    model = Course
    fields = ['name', 'start', 'end', 'school', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CourseUpdateView(UpdateView):
    model = Course
    fields = ['name', 'start', 'end', 'school', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ExperienceCreateView(CreateView):
    model = Experience
    fields = ['position', 'company', 'start', 'end', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ExperienceUpdateView(UpdateView):
    model = Experience
    fields = ['position', 'company', 'start', 'end', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PortfolioCreateView(CreateView):
    model = Portfolio
    fields = ['name', 'description', 'link', 'cover']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PortfolioUpdateView(UpdateView):
    model = Portfolio
    fields = ['name', 'description', 'link', 'cover']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SkillCreateView(CreateView):
    model = Skill
    fields = ['name', 'description', 'level']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SkillUpdateView(UpdateView):
    model = Skill
    fields = ['name', 'description', 'level']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class HobbyCreateView(CreateView):
    model = Hobby
    fields = ['name']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class HobbyUpdateView(UpdateView):
    model = Hobby
    fields = ['name']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class LanguageCreateView(CreateView):
    model = Language
    fields = ['name', 'level']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class LanguageUpdateView(UpdateView):
    model = Language
    fields = ['name', 'level']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CocurricularCreateView(CreateView):
    model = Cocurricular
    fields = ['activity', 'company', 'start', 'end', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CocurricularUpdateView(UpdateView):
    model = Cocurricular
    fields = ['activity', 'company', 'start', 'end', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ReferenceCreateView(CreateView):
    model = Reference
    fields = ['name', 'position', 'company', 'phone', 'email']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ReferenceUpdateView(UpdateView):
    model = Reference
    fields = ['name', 'position', 'company', 'phone', 'email']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('usercv:user-profile')
    return render(request, 'registration/register.html', {'form': form})


def user_profile(request):
    prof = Profile.objects.get(user=request.user)
    return render(request, 'usercv/user_profile.html', {'prof': prof})


def cv_view(request):
    abouts = About.objects.filter(user=request.user)
    educations = Education.objects.filter(user=request.user)
    careers = Career.objects.filter(user=request.user)
    courses = Course.objects.filter(user=request.user)
    experiences = Experience.objects.filter(user=request.user)
    portfolios = Portfolio.objects.filter(user=request.user)
    skills = Skill.objects.filter(user=request.user)
    hobbies = Hobby.objects.filter(user=request.user)
    languages = Language.objects.filter(user=request.user)
    cocurriculars = Cocurricular.objects.filter(user=request.user)
    references = Reference.objects.filter(user=request.user)
    context = {
        'abouts': abouts,
        'educations': educations,
        'careers': careers,
        'courses': courses,
        'experiences': experiences,
        'portfolios': portfolios,
        'skills': skills,
        'hobbies': hobbies,
        'languages': languages,
        'cocurriculars': cocurriculars,
        'references': references,
    }
    return render(request, 'usercv/user_cv.html', context)

usercv/templates/usercv/about_form.html
{% extends 'usercv/base.html' %}

{% load crispy_forms_tags %}
{% block title %}profile{% endblock %}

{% block content %}
     <br>
    <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
    <div class="card card-body">
        <h4 class="text-info ml-5">About</h4><hr>
        <form class="form-horizontal mr-5 ml-5" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-info">{% if object %}Update{% else %}Submit{% endif %}</button>
            </div>
        </form>
    </div>
    </div>
    </div>
{% endblock %}

usercv/templates/usercv/base.html
{% load static %}
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<link href="{% static 'usercv/css/main.css' %}" type="text/css" rel="stylesheet">
</head>

<body>
<div class="container-fluid">
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'usercv:cv-index' %}" style="color: steelblue;"><i class="fas fa-user"></i> CV Builder</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ml-5">
<li class="nav-item">
        <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
        </form>
        </li>
    </ul>

      <ul class="navbar-nav navbar-right">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'usercv:create-cv' %}"><i class="fas fa-plus"></i>&nbsp;Create CV</a>
      </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
          </li>
          {% endif %}

    </ul>

  </div>
</nav>
</div>
    {% block content %}

    {% endblock %}

</body>
</html>

usercv/templates/usercv/career_form.html
{% extends 'usercv/base.html' %}

{% load crispy_forms_tags %}
{% block title %}career{% endblock %}

{% block content %}
     <br>
    <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
    <div class="card card-body">
        <h4 class="text-info ml-5">Career</h4><hr>
        <form class="form-horizontal mr-5 ml-5" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-info">{% if object %}Update{% else %}Submit{% endif %}</button>
            </div>
        </form>
    </div>
    </div>
    </div>
{% endblock %}

usercv/templates/usercv/cocurricular_form.html
{% extends 'usercv/base.html' %}

{% load crispy_forms_tags %}
{% block title %}cocurricukar{% endblock %}

{% block content %}
     <br>
    <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
    <div class="card card-body">
        <h4 class="text-info ml-5">Co-curricular</h4><hr>
        <form class="form-horizontal mr-5 ml-5" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-info">{% if object %}Update{% else %}Submit{% endif %}</button>
            </div>
        </form>
    </div>
    </div>
    </div>
{% endblock %}

usercv/templates/usercv/course_form.html
{% extends 'usercv/base.html' %}

{% load crispy_forms_tags %}
{% block title %}course{% endblock %}

{% block content %}
     <br>
    <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
    <div class="card card-body">
        <h4 class="text-info ml-5">Course</h4><hr>
        <form class="form-horizontal mr-5 ml-5" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-info">{% if object %}Update{% else %}Submit{% endif %}</button>
            </div>
        </form>
    </div>
    </div>
    </div>
{% endblock %}

usercv/templates/usercv/user_cv.html
{% extends 'usercv/base.html' %}
{% block title %}{{ user.username }}{% endblock %}

{% block content %}

    <br>
    <div class="row">

        <div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">About</h4><hr>
        {% if abouts %}
            {% for about in abouts %}
                <h4>{{ about.title }}</h4>
                <p>{{ about.description }}</p>
            {% endfor %}
        {% endif %}
        <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:about-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>

  </div>
</div>

<div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">Education</h4><hr>
        {% if educations %}
            {% for education in educations %}
                <h4>{{ education.title }}</h4>
                <h5>{{ education.school }}</h5>
                <p>{{ education.description }}</p>
                <p><small>From:&nbsp;{{ education.start }}</small><small style="float:right;">To:&nbsp;{{ education.end }}</small></p>
            {% endfor %}
        {% endif %}
        <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:education-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>
  </div>
</div>

<div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">Career</h4><hr>
        {% if careers %}
            {% for career in careers %}
                <h4>{{ career.title }}</h4>
                <p>{{ career.description }}</p>
            {% endfor %}
        {% endif %}
        <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:career-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>
  </div>
</div>
    </div>


    <div class="row">
<div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">Course</h4><hr>
        {% if courses %}
            {% for course in courses %}
                <h4>{{ course.title }}</h4>
                <h5>{{ course.school }}</h5>
                <P>{{ course.description }}</P>
                <p><small>From:&nbsp;{{ course.start }}</small><small style="float:right;">To:&nbsp;{{ course.end }}</small></p>
            {% endfor %}
        {% endif %}
      <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:course-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>
  </div>
</div>

<div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">Experience</h4><hr>
        {% if experiences %}
            {% for experience in experiences %}
                <h4>{{ experience.title }}</h4>
                <h5>{{ experience.company }}</h5>
                <p>{{ experience.description }}</p>
                <p><small>From:&nbsp;{{ experience.start }}</small><small style="float:right;">To:&nbsp;{{ experience.end }}</small></p>
            {% endfor %}
        {% endif %}
        <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:experience-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>

  </div>
</div>

<div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">Portfolio</h4><hr>
        {% if portfolios %}
            {% for portfolio in portfolios %}
                <h4>{{ portfolio.name }}</h4>
                <p>{{ portfolio.description }}</p>
                <p><a href="{{ portfolio.link }}"> {{ portfolio.link }}</a></p>
            {% endfor %}
        {% endif %}
        <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:portfolio-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>

  </div>
</div>
    </div>


    <div class="row">
<div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">Skills</h4><hr>
        {% if skills %}
            {% for skill in  skills %}
                <h4>{{ skill.name }}</h4>
                <p>{{skill.description }}</p>
                <p><small>Level:&nbsp;{{ skill.level }}</small></p>
            {% endfor %}

        {% endif %}
        <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:skill-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>
  </div>
</div>


    <div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">Hobbies</h4><hr>
        {% if hobbies %}
            {% for hobby in hobbies %}
                <p>{{ hobby.name }}</p>
            {% endfor %}
        {% endif %}
        <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:hobby-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>

  </div>
</div>

    <div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">Language</h4><hr>
        {% if languages %}
            <table class="table">
            {% for language in languages %}
                <tr>
                <td>{{ language.name }}</td><td>{{ language.level }}</td>
                </tr>
            {% endfor %}
            </table>
        {% endif %}
        <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:language-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>

  </div>
</div>
    </div>

    <div class="row">
    <div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">Co-Curricular</h4><hr>
        {% if cocurriculars %}
            {% for co in cocurriculars %}
                <h4>{{ co.company }}</h4>
                <h5>{{ co.activity }}</h5>
                <p>{{ co.description }}</p>
                <p><small>From:&nbsp;{{ co.start }}</small><small style="float:right;">To:&nbsp;{{ co.end }}</small></p>
            {% endfor %}
        {% endif %}
        <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:cocurricular-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>

  </div>
</div>

    <div class="col-sm-4">
    <div class="content-section">
<h4 class="text-info">References</h4><hr>
        {% if references %}
            {% for referee in references %}
                <p>{{ referee.name }}</p>
                <p>{{ referee.position }}</p>
                <p>{{ referee.company }}</p>
                <p>{{ referee.email }}</p>
                <p>{{ referee.phone }}</p>
            {% endfor %}
        {% endif %}
        <a class="btn btn-info btn-sn mt-1" href="{% url 'usercv:reference-create' %}"><i class="fas fa-plus-circle"></i> </a>
        <a class="btn btn-secondary btn-sn mt-1" href=""><i class="fas fa-info"></i> </a>

  </div>
</div>
    </div>
{% endblock %}

usercv/templates/usercv/user_profile.html
{% extends 'usercv/base.html' %}
{% block title %}{{ user.username }}{% endblock %}

{% block content %}
<div class="row">
<div class="col-sm-3">
    <div class="content-section">
        <h4 class="text-info">Profile</h4><hr>
    <div class="media">
    <img class="rounded-circle account-img" src="{{ prof.image.url }}" alt="">
  </div>
        <p>{{ user.email }}</p>
        <p>{{ prof.website }}</p>

        <p><a class="btn btn-secondary btn-sn mt-1" href="{% url 'usercv:profile-update'  user.id%}">Update</a></p>
  </div>
</div>

<div class="col-sm-9">
    <div class="content-section">
        <h3 class="text-info">My Resume</h3>
        <hr>

    </div>
</div>


</div>
{% endblock %}